Backend/project/apps/accountings/urls.py
# URL
from django.urls import path, include

# Views
from . import views

# FILTROS

# Decorador
from django.contrib.auth.decorators import login_required

# Routes
from apps.accountings.api import routers


app_name = 'contable'

urlpatterns = [
    path('',views.list_modulos,name='modulos_contables'),
    path('reports/acreedores/',login_required(views.reportes_generales_acreedores),name='reportes_acreedores'),
    path('reports/seguros/',login_required(views.reportes_generales_seguros),name='reportes_seguros'),
    # LIST
    path('acreedores/', views.AcreedoresListView.as_view(), name='acreedores'),
    path('seguros/', views.SeguroListView.as_view(), name='seguros'),
    path('ingresos/', login_required( views.IngresosList.as_view()), name='ingresos'),
    path('egresos/', login_required(views.EgresosList.as_view()), name='egresos'),

    # CREATE
    path('acreedores/create/', views.add_acreedor, name='acreedores_create'),
    path('seguros/create/', views.add_seguro, name='seguros_create'),
    path('ingresos/create/', views.add_ingreso, name='ingresos_create'),
    path('egresos/create/', views.add_egresos, name='egresos_create'),

    # DETAIL
    path('acreedores/detail/<int:id>/', views.detail_acreedores, name='acreedores_detail'),
    path('seguros/detail/<int:id>/', views.detail_seguro, name='seguros_detail'),
    path('ingresos/detail/<int:id>/', views.detail_ingreso, name='ingresos_detail'),
    path('egresos/detail/<int:id>/', views.detail_egreso, name='egresos_detail'),

    # BOLETAS
    path('seguros/boleta/', views.add_boleta_seguro, name='seguros_boleta'),
    path('acreedores/boleta/', views.add_boleta_acreedor, name='acreedores_boleta'),

    # UPDATE
    path('egresos/update/<int:id>/',views.actualizar_egresos, name='egresos_update'),
    path('ingresos/update/<int:id>/',views.actualizar_ingresos, name='ingresos_update'),


    # SEARCH 
    path('acreedores/search/', views.AcreedoresSearch.as_view(), name='acreedores_search'),
    path('seguros/search/', views.SeguroSearch.as_view(), name='seguros_search'),
    path('ingresos/search/', views.IngresoSearch.as_view(), name='ingresos_search'),
    path('egresos/search/', views.EgresoSearch.as_view(), name='egresos_search'),

    # FILTRO
    path('ingresos/pendiente/', views.pendiente_ingresos_vincular, name='pendiente_ingresos_vincular'),
    path('ingresos/completados/', views.ingresos_vinculados, name='ingresos_vinculados'),

    path('egresos/pendiente/', views.pendiente_egresos_vincular, name='pendiente_egresos_vincular'),
    path('egresos/completados/', views.egresos_vinculados, name='egresos_vinculados'),
    
    path('seguros/seguros_cancelados/',views.seguro_cancelado, name='seguro_cancelado'),
    path('seguros/atraso_en_aportacion/',views.seguros_atraso_aportacion, name='seguros_atraso_aportacion'),
    path('seguros/atraso_por_fechas/',views.seguros_atraso_fechas, name='seguros_atraso_fechas'),

    path('acreedores/acreedores_cancelados/',views.acreedores_cancelado, name='acreedores_cancelado'),
    path('acreedores/atraso_en_aportacion/',views.acreedores_atraso_aportacion, name='acreedores_atraso_aportacion'),
    path('acreedores/atraso_por_fechas/',views.acreedores_atraso_fechas, name='acreedores_atraso_fechas'),

    
]

urlpatterns+=routers.urlpatterns

Backend/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

# Vistas
from . import views
from apps.actividades.views  import subida_documento

from django.contrib.auth import views as auth_views
from . import generate_pdf



# CONFIGURANCION PARA MANEJAR LOS STATICS Y MEDIA
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required



from django.conf.urls import handler404, handler500, handler400, handler403
from .http import request_400

from django.core.mail import send_mail
from django.conf import settings

from django.urls import re_path
from django.views.static import serve
from django.conf import settings

# RUTAS
from .rutas import urlpatterns_apps, urlpatterns_api, urlpatterns_reports, urlpatterns_http


urlpatterns = [    
    path('',login_required(views.index),name='index'),
    path('accounts/login/',views.login_view, name='login'),
    path('verification/', views.verification, name='verification'),
    path('logout/',views.logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('search/', login_required(views.Search.as_view()), name='busqueda_general'),
    path('qr/<str:data>/', views.generate_qr, name='generate_qr'),
    path('pdf/<int:id>', generate_pdf.generar_pdf, name='pdf'),
    path('boleta_procesada/', views.agradecimeinto, name='boleta_procesada'),
    path('cliente/<str:uuid>/', subida_documento, name='subida_documento_cliente'),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += urlpatterns_apps + urlpatterns_api + urlpatterns_reports + urlpatterns_http

#template_name='user/autentication/password-reset.html'
#email_template_name='user/autentication/password-message.html'

handler404 = request_400.error404

Backend/project/apps/accountings/views/search.py
# Manejo de mensajes
from django.contrib import messages

# Models
from apps.accountings.models import Creditor, Insurance,  Income


# LIBRERIAS PARA CRUD
from django.views.generic.list import ListView
from django.db.models import Q

# Decoradores
from project.decorador import  permiso_requerido
from django.utils.decorators import method_decorator

# Scripts
from scripts.recoleccion_permisos import recorrer_los_permisos_usuario

# MENSAJES
from django.contrib import messages

class AcreedoresSearch(ListView):
    template_name = 'contable/acreedores/list.html'
    paginate_by = 25

    def get_queryset(self):
        try:
            # Asignar la consulta a una variable local
            query = self.query()

            # Crear una lista para almacenar los filtros
            filters = Q()

            # Añadir filtros si la consulta no está vacía
            if query:
                filters |= Q(fecha_inicio__icontains=query)
                filters |= Q(fecha_vencimiento__icontains=query)                
                filters |= Q(nombre_acreedor__icontains=query)                
                filters |= Q(codigo_acreedor__icontains=query)
                filters |= Q(numero_referencia__icontains=query)

                # Si la consulta es numérica, usar filtro exacto para campos numéricos
                if query.isdigit():
                    filters |= Q(monto__exact=query)
                    filters |= Q(plazo__exact=query)
                    filters |= Q(tasa__exact=query)
                    

            # Filtrar los objetos Banco usando los filtros definidos
            return Creditor.objects.filter(filters)
        except Exception as e:
            # Manejar cualquier excepción que ocurra y devolver un queryset vacío
            print(f"Error al filtrar el queryset: {e}")
            return Creditor.objects.none()
    

    def query(self):
        return self.request.GET.get('q')
    
    @method_decorator(permiso_requerido('puede_consultar_acreedores'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not (context['object_list']):
            messages.error(self.request,'No se encontrado ningun dato')
        context['query'] = self.query()
        context['title'] = f'Registro de Acreedores con {self.query()}'
        context['count'] = context['object_list'].count()
        context['posicion'] = self.query()
        context['acreedores_list']  = context['object_list']
        context['permisos'] = recorrer_los_permisos_usuario(self.request)
        return context

class SeguroSearch(ListView):
    template_name = 'contable/seguros/list.html'
    paginate_by = 25

    def get_queryset(self):
        try:
            # Asignar la consulta a una variable local
            query = self.query()

            # Crear una lista para almacenar los filtros
            filters = Q()

            # Añadir filtros si la consulta no está vacía
            if query:
                filters |= Q(fecha_inicio__icontains=query)
                filters |= Q(fecha_vencimiento__icontains=query)                
                filters |= Q(nombre_acreedor__icontains=query)                
                filters |= Q(codigo_seguro__icontains=query)
                filters |= Q(numero_referencia__icontains=query)
                

                # Si la consulta es numérica, usar filtro exacto para campos numéricos
                if query.isdigit():
                    filters |= Q(monto__exact=query)
                    filters |= Q(plazo__exact=query)
                    filters |= Q(tasa__exact=query)
                    

            # Filtrar los objetos Banco usando los filtros definidos
            return Insurance.objects.filter(filters)
        except Exception as e:
            # Manejar cualquier excepción que ocurra y devolver un queryset vacío
            print(f"Error al filtrar el queryset: {e}")
            return Insurance.objects.none()
    

    def query(self):
        return self.request.GET.get('q')
    
    @method_decorator(permiso_requerido('puede_consultar_seguros'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not (context['object_list']):
            messages.error(self.request,'No se encontrado ningun dato')
        context['query'] = self.query()
        context['title'] = f'Registro de Seguros con {self.query()}.'
        context['count'] = context['object_list'].count()
        context['posicion'] = self.query()
        context['object_list']  = context['object_list']
        context['permisos'] = recorrer_los_permisos_usuario(self.request)
        return context

class IngresoSearch(ListView):
    template_name = 'contable/ingresos/list.html'
    paginate_by = 25

    def get_queryset(self):
        try:
            # Asignar la consulta a una variable local
            query = self.query()

            # Crear una lista para almacenar los filtros
            filters = Q()

            # Añadir filtros si la consulta no está vacía
            if query:
                filters |= Q(fecha__icontains=query)
                filters |= Q(codigo_ingreso__icontains=query)                
                           
                
                filters |= Q(numero_referencia__icontains=query)

                # Si la consulta es numérica, usar filtro exacto para campos numéricos
                if query.isdigit():
                    filters |= Q(monto__exact=query)
                    
                    
                    

            # Filtrar los objetos Banco usando los filtros definidos
            return Income.objects.filter(filters)
        except Exception as e:
            # Manejar cualquier excepción que ocurra y devolver un queryset vacío
            print(f"Error al filtrar el queryset: {e}")
            return Income.objects.none()
    

    def query(self):
        return self.request.GET.get('q')
    
    @method_decorator(permiso_requerido('puede_consultar_ingresos'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not (context['object_list']):
            messages.error(self.request,'No se encontrado ningun dato')
        context['query'] = self.query()
        context['title'] = f'Registro de Ingresos con {self.query()}'
        context['count'] = context['object_list'].count()
        context['posicion'] = self.query()
        context['object_list']  = context['object_list']
        context['permisos'] = recorrer_los_permisos_usuario(self.request)
        return context

class EgresoSearch(ListView):
    template_name = 'contable/egresos/list.html'
    paginate_by = 25

    def get_queryset(self):
        try:
            # Asignar la consulta a una variable local
            query = self.query()

            # Crear una lista para almacenar los filtros
            filters = Q()

            # Añadir filtros si la consulta no está vacía
            if query:
                filters |= Q(fecha__icontains=query)
                filters |= Q(fecha_doc_fiscal__icontains=query)                
                filters |= Q(numero_doc__icontains=query)                
                filters |= Q(codigo_seguro__icontains=query)
                filters |= Q(numero_referencia__icontains=query)
                

                # Si la consulta es numérica, usar filtro exacto para campos numéricos
                if query.isdigit():
                    filters |= Q(monto__exact=query)
                    filters |= Q(plazo__exact=query)
                    filters |= Q(tasa__exact=query)
                    

            # Filtrar los objetos Banco usando los filtros definidos
            return Insurance.objects.filter(filters)
        except Exception as e:
            # Manejar cualquier excepción que ocurra y devolver un queryset vacío
            print(f"Error al filtrar el queryset: {e}")
            return Insurance.objects.none()
    

    def query(self):
        return self.request.GET.get('q')
    
    @method_decorator(permiso_requerido('puede_consultar_egresos'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not (context['object_list']):
            messages.error(self.request,'No se encontrado ningun dato')
        context['query'] = self.query()
        context['title'] = f'Registro de Egresos con {self.query()}'
        context['count'] = context['object_list'].count()
        context['posicion'] = self.query()
        context['object_list']  = context['object_list']
        context['permisos'] = recorrer_los_permisos_usuario(self.request)
        return context

Backend/project/apps/customers/views/filter.py
from django.shortcuts import render, get_object_or_404, redirect

# Decoradores
from django.contrib.auth.decorators import login_required
from project.decorador import permiso_requerido

# SCRIPTS
from scripts.recoleccion_permisos import recorrer_los_permisos_usuario

@login_required
@permiso_requerido('puede_visualizar_el_registro_clientes')
def list_filters(request):
    template_name = 'customer/options.html'
    context = {
        'title':'EL TELAR / REPORTES - CLIENTES',
        'posicion':'Clientes',
        'permisos':recorrer_los_permisos_usuario(request)
    }

    return render(request, template_name, context)

Backend/project/apps/customers/views/search.py
# Models
from apps.customers.models import Customer

# LIBRERIAS PARA CRUD
from django.views.generic.list import ListView
from django.db.models import Q

# Decoradores
from project.decorador import permiso_requerido
from django.utils.decorators import method_decorator




# MENSAJES
from django.contrib import messages



# SCRIPTS
from scripts.recoleccion_permisos import recorrer_los_permisos_usuario

# ----- BUSCAR CLIENTES ----- #
class CustomerSearch(ListView):
    template_name = 'customer/list.html'
    

    def get_queryset(self):
        try:
            # Asignar la consulta a una variable local
            query = self.query()

            filters = Q()


            # Definir los filtros utilizando Q objects
            filters |= Q(first_name__icontains=query) 
            filters |= Q(customer_code__icontains=query)
            filters |= Q(last_name__icontains=query)
            filters |= Q(type_identification__icontains=query)
            filters |= Q(gender__icontains=query)

 
            # Filtrar los objetos Customer usando los filtros definidos
            return Customer.objects.filter(filters)
        except Exception as e:
            # Manejar cualquier excepción que ocurra y devolver un queryset vacío
            print(f"Error al filtrar el queryset: {e}")
            
            return Customer.objects.none()
    

    def query(self):
        return self.request.GET.get('q')
    
    @method_decorator([permiso_requerido('puede_realizar_consultar_de_clientes')])
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not (context['object_list']):
            messages.error(self.request,'No se encontrado ningun dato')
        context['query'] = self.query()
        context['title'] = f'Consulta de Clientes. {self.query()}'
        context['count'] = context['customer_list'].count()
        context['posicion'] = self.query() 
        context['permisos'] = recorrer_los_permisos_usuario(self.request)
        

        return context

Backend/project/templates/contable/egresos/snippets/filters.html
{% load static %}
<div class="dropdown">
    <button style="border: none; background-color: white;" type="button" data-bs-toggle="dropdown"
        aria-expanded="false">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-filter"
            viewBox="0 0 16 16">
            <path
                d="M6 10.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5m-2-3a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m-2-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5" />
        </svg>
    </button>


    <ul class="dropdown-menu ">
        <li><a class="dropdown-item fw-bold" href="{% url 'contable:egresos' %}">Todos </a></li>
        <li><a class="dropdown-item fw-normal" href="{% url 'contable:pendiente_egresos_vincular' %}">Pendientes de Vincular </a></li>
        <li><a class="dropdown-item fw-normal" href="{% url 'contable:egresos_vinculados' %}">Vinculados </a>
        </li>
        
    </ul>

</div>

Backend/project/templates/contable/egresos/snippets/presentation.html
{% load static %}

<div style="padding: 2.5rem">
    <h3>¡Bienvenido al Apartado de <span class="badge text-bg-dark">Egresos</span> !</h3>
    <div class="d-flex justify-content-center fs-5">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Inicio</a></li>
                
                <li class="breadcrumb-item"><a href="{% url 'contable:egresos' %}">Egresos</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{posicion}}</li>

            </ol>
        </nav>
    </div>

    <p>
        En este módulo, podrás gestionar toda la información relacionada con los Egresos de manera eficiente y
        organizada.
    </p>
    <p>
        Este módulo está diseñado para brindarte el control y la flexibilidad
        necesarios para administrar eficazmente el registro de los Egresos en la
        plataforma.
    </p>
</div>

Backend/project/templates/contable/egresos/snippets/search.html
{%load static %}
<nav>
    <div class="container-fluid">
        <form class="d-flex" id="searchForm" action="{% url 'contable:egresos' %}">
            <div class="input-group">
                <input class="form-control me-2" name="q" value="{{ query }}" type="search" placeholder="Buscar"
                    aria-label="Search">

                
                <select name="mes" id="mes" class="form-control me-2">
                    <option value="1" {% if mes == 1 %}selected{% endif %}>Enero</option>
                    <option value="2" {% if mes == 2 %}selected{% endif %}>Febrero</option>
                    <option value="3" {% if mes == 3 %}selected{% endif %}>Marzo</option>
                    <option value="4" {% if mes == 4 %}selected{% endif %}>Abril</option>
                    <option value="5" {% if mes == 5 %}selected{% endif %}>Mayo</option>
                    <option value="6" {% if mes == 6 %}selected{% endif %}>Junio</option>
                    <option value="7" {% if mes == 7 %}selected{% endif %}>Julio</option>
                    <option value="8" {% if mes == 8 %}selected{% endif %}>Agosto</option>
                    <option value="9" {% if mes == 9 %}selected{% endif %}>Septiembre</option>
                    <option value="10" {% if mes == 10 %}selected{% endif %}>Octubre</option>
                    <option value="11" {% if mes == 11 %}selected{% endif %}>Noviembre</option>
                    <option value="12" {% if mes == 12 %}selected{% endif %}>Diciembre</option>
                </select>

                <input type="number" name="anio" id="anio" value="{{ anio }}" class="form-control me-2">

                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>


    </div>
</nav>

<script>
    document.getElementById("searchForm").addEventListener("submit", function (e) {
        // Selecciona cualquier input, select o textarea
        const qInput = this.querySelector("[name='q']");
        const anioInput = this.querySelector("[name='anio']");
        const mesInput = this.querySelector("[name='mes']");

        if (qInput && !qInput.value.trim()) {
            qInput.removeAttribute("name"); // elimina si está vacío
        }
        if (anioInput && !anioInput.value.trim()) {
            anioInput.removeAttribute("name");
        }
        if (mesInput && !mesInput.value.trim()) {
            mesInput.removeAttribute("name");
        }
    });
</script>