Backend/project/apps/customers/urls.py
# URL
from django.urls import path, include

# Views
from . import views

# FILTROS
from . import filters
# Decorador
from django.contrib.auth.decorators import login_required

# Routes
from apps.customers.api import routers
from .rutas import urlpatterns_asesores_creditos

app_name = 'customers'

urlpatterns = [
    path('', login_required(views.CustomerFiltro.as_view()), name='customers'),
    path('create/', views.add_customer, name='create_customer'),
    path('created/', views.create_customer, name='create'), 
    path('update/<str:customer_code>/', views.update_customer, name='update_customer'),
    path('search/', login_required(views.CustomerSearch.as_view()), name='search'),
    path('delete/<int:id>/',views.delete_customer,name='delete'),
    path('delete_customer/<int:id>/',views.delete_customers,name='delete_customer'),
    path('formulario_ive/<int:id>/', login_required(views.formulario_ive), name='formulario_ive'),
    path('detail/<str:customer_code>/', login_required(views.detail_customer), name='detail'),
    path('recent/', login_required(filters.recent_customer), name='recent'),
    path('solicitude/', login_required(filters.solicitude_customer), name='solicitude'),
    path('not_accepted/', login_required(filters.not_accepted_customer), name='not_accepted'),
    path('accepted/', login_required(filters.accepted_customer), name='accepted'),
    path('inactive/', login_required(filters.inactive_customer), name='inactive'),
    path('document_review/', login_required(filters.document_review_customer), name='document_review'),
    path('clasificacion/',views.list_filters, name='list_filters'),


    
]

urlpatterns+=routers.urlpatterns + urlpatterns_asesores_creditos

Backend/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

# Vistas
from . import views
from apps.actividades.views  import subida_documento

from django.contrib.auth import views as auth_views
from . import generate_pdf



# CONFIGURANCION PARA MANEJAR LOS STATICS Y MEDIA
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required



from django.conf.urls import handler404, handler500, handler400, handler403
from .http import request_400

from django.core.mail import send_mail
from django.conf import settings

from django.urls import re_path
from django.views.static import serve
from django.conf import settings

# RUTAS
from .rutas import urlpatterns_apps, urlpatterns_api, urlpatterns_reports, urlpatterns_http


urlpatterns = [    
    path('',login_required(views.index),name='index'),
    path('accounts/login/',views.login_view, name='login'),
    path('verification/', views.verification, name='verification'),
    path('logout/',views.logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('search/', login_required(views.Search.as_view()), name='busqueda_general'),
    path('qr/<str:data>/', views.generate_qr, name='generate_qr'),
    path('pdf/<int:id>', generate_pdf.generar_pdf, name='pdf'),
    path('boleta_procesada/', views.agradecimeinto, name='boleta_procesada'),
    path('cliente/<str:uuid>/', subida_documento, name='subida_documento_cliente'),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += urlpatterns_apps + urlpatterns_api + urlpatterns_reports + urlpatterns_http

#template_name='user/autentication/password-reset.html'
#email_template_name='user/autentication/password-message.html'

handler404 = request_400.error404

Backend/project/apps/accountings/views/search.py
# Manejo de mensajes
from django.contrib import messages

# Models
from apps.accountings.models import Creditor, Insurance,  Income


# LIBRERIAS PARA CRUD
from django.views.generic.list import ListView
from django.db.models import Q

# Decoradores
from project.decorador import  permiso_requerido
from django.utils.decorators import method_decorator

# Scripts
from scripts.recoleccion_permisos import recorrer_los_permisos_usuario

# MENSAJES
from django.contrib import messages

class AcreedoresSearch(ListView):
    template_name = 'contable/acreedores/list.html'
    paginate_by = 25

    def get_queryset(self):
        try:
            # Asignar la consulta a una variable local
            query = self.query()

            # Crear una lista para almacenar los filtros
            filters = Q()

            # Añadir filtros si la consulta no está vacía
            if query:
                filters |= Q(fecha_inicio__icontains=query)
                filters |= Q(fecha_vencimiento__icontains=query)                
                filters |= Q(nombre_acreedor__icontains=query)                
                filters |= Q(codigo_acreedor__icontains=query)
                filters |= Q(numero_referencia__icontains=query)

                # Si la consulta es numérica, usar filtro exacto para campos numéricos
                if query.isdigit():
                    filters |= Q(monto__exact=query)
                    filters |= Q(plazo__exact=query)
                    filters |= Q(tasa__exact=query)
                    

            # Filtrar los objetos Banco usando los filtros definidos
            return Creditor.objects.filter(filters)
        except Exception as e:
            # Manejar cualquier excepción que ocurra y devolver un queryset vacío
            print(f"Error al filtrar el queryset: {e}")
            return Creditor.objects.none()
    

    def query(self):
        return self.request.GET.get('q')
    
    @method_decorator(permiso_requerido('puede_consultar_acreedores'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not (context['object_list']):
            messages.error(self.request,'No se encontrado ningun dato')
        context['query'] = self.query()
        context['title'] = f'Registro de Acreedores con {self.query()}'
        context['count'] = context['object_list'].count()
        context['posicion'] = self.query()
        context['acreedores_list']  = context['object_list']
        context['permisos'] = recorrer_los_permisos_usuario(self.request)
        return context

class SeguroSearch(ListView):
    template_name = 'contable/seguros/list.html'
    paginate_by = 25

    def get_queryset(self):
        try:
            # Asignar la consulta a una variable local
            query = self.query()

            # Crear una lista para almacenar los filtros
            filters = Q()

            # Añadir filtros si la consulta no está vacía
            if query:
                filters |= Q(fecha_inicio__icontains=query)
                filters |= Q(fecha_vencimiento__icontains=query)                
                filters |= Q(nombre_acreedor__icontains=query)                
                filters |= Q(codigo_seguro__icontains=query)
                filters |= Q(numero_referencia__icontains=query)
                

                # Si la consulta es numérica, usar filtro exacto para campos numéricos
                if query.isdigit():
                    filters |= Q(monto__exact=query)
                    filters |= Q(plazo__exact=query)
                    filters |= Q(tasa__exact=query)
                    

            # Filtrar los objetos Banco usando los filtros definidos
            return Insurance.objects.filter(filters)
        except Exception as e:
            # Manejar cualquier excepción que ocurra y devolver un queryset vacío
            print(f"Error al filtrar el queryset: {e}")
            return Insurance.objects.none()
    

    def query(self):
        return self.request.GET.get('q')
    
    @method_decorator(permiso_requerido('puede_consultar_seguros'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not (context['object_list']):
            messages.error(self.request,'No se encontrado ningun dato')
        context['query'] = self.query()
        context['title'] = f'Registro de Seguros con {self.query()}.'
        context['count'] = context['object_list'].count()
        context['posicion'] = self.query()
        context['object_list']  = context['object_list']
        context['permisos'] = recorrer_los_permisos_usuario(self.request)
        return context

class IngresoSearch(ListView):
    template_name = 'contable/ingresos/list.html'
    paginate_by = 25

    def get_queryset(self):
        try:
            # Asignar la consulta a una variable local
            query = self.query()

            # Crear una lista para almacenar los filtros
            filters = Q()

            # Añadir filtros si la consulta no está vacía
            if query:
                filters |= Q(fecha__icontains=query)
                filters |= Q(codigo_ingreso__icontains=query)                
                           
                
                filters |= Q(numero_referencia__icontains=query)

                # Si la consulta es numérica, usar filtro exacto para campos numéricos
                if query.isdigit():
                    filters |= Q(monto__exact=query)
                    
                    
                    

            # Filtrar los objetos Banco usando los filtros definidos
            return Income.objects.filter(filters)
        except Exception as e:
            # Manejar cualquier excepción que ocurra y devolver un queryset vacío
            print(f"Error al filtrar el queryset: {e}")
            return Income.objects.none()
    

    def query(self):
        return self.request.GET.get('q')
    
    @method_decorator(permiso_requerido('puede_consultar_ingresos'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not (context['object_list']):
            messages.error(self.request,'No se encontrado ningun dato')
        context['query'] = self.query()
        context['title'] = f'Registro de Ingresos con {self.query()}'
        context['count'] = context['object_list'].count()
        context['posicion'] = self.query()
        context['object_list']  = context['object_list']
        context['permisos'] = recorrer_los_permisos_usuario(self.request)
        return context

class EgresoSearch(ListView):
    template_name = 'contable/egresos/list.html'
    paginate_by = 25

    def get_queryset(self):
        try:
            # Asignar la consulta a una variable local
            query = self.query()

            # Crear una lista para almacenar los filtros
            filters = Q()

            # Añadir filtros si la consulta no está vacía
            if query:
                filters |= Q(fecha__icontains=query)
                filters |= Q(fecha_doc_fiscal__icontains=query)                
                filters |= Q(numero_doc__icontains=query)                
                filters |= Q(codigo_seguro__icontains=query)
                filters |= Q(numero_referencia__icontains=query)
                

                # Si la consulta es numérica, usar filtro exacto para campos numéricos
                if query.isdigit():
                    filters |= Q(monto__exact=query)
                    filters |= Q(plazo__exact=query)
                    filters |= Q(tasa__exact=query)
                    

            # Filtrar los objetos Banco usando los filtros definidos
            return Insurance.objects.filter(filters)
        except Exception as e:
            # Manejar cualquier excepción que ocurra y devolver un queryset vacío
            print(f"Error al filtrar el queryset: {e}")
            return Insurance.objects.none()
    

    def query(self):
        return self.request.GET.get('q')
    
    @method_decorator(permiso_requerido('puede_consultar_egresos'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not (context['object_list']):
            messages.error(self.request,'No se encontrado ningun dato')
        context['query'] = self.query()
        context['title'] = f'Registro de Egresos con {self.query()}'
        context['count'] = context['object_list'].count()
        context['posicion'] = self.query()
        context['object_list']  = context['object_list']
        context['permisos'] = recorrer_los_permisos_usuario(self.request)
        return context

Backend/project/apps/customers/views/search.py
# Models
from apps.customers.models import Customer

# LIBRERIAS PARA CRUD
from django.views.generic.list import ListView
from django.db.models import Q

# Decoradores
from project.decorador import permiso_requerido
from django.utils.decorators import method_decorator




# MENSAJES
from django.contrib import messages



# SCRIPTS
from scripts.recoleccion_permisos import recorrer_los_permisos_usuario

# ----- BUSCAR CLIENTES ----- #
class CustomerSearch(ListView):
    template_name = 'customer/list.html'
    

    def get_queryset(self):
        try:
            # Asignar la consulta a una variable local
            query = self.query()

            filters = Q()


            # Definir los filtros utilizando Q objects
            filters |= Q(first_name__icontains=query) 
            filters |= Q(customer_code__icontains=query)
            filters |= Q(last_name__icontains=query)
            filters |= Q(type_identification__icontains=query)
            filters |= Q(gender__icontains=query)

 
            # Filtrar los objetos Customer usando los filtros definidos
            return Customer.objects.filter(filters)
        except Exception as e:
            # Manejar cualquier excepción que ocurra y devolver un queryset vacío
            print(f"Error al filtrar el queryset: {e}")
            
            return Customer.objects.none()
    

    def query(self):
        return self.request.GET.get('q')
    
    @method_decorator([permiso_requerido('puede_realizar_consultar_de_clientes')])
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not (context['object_list']):
            messages.error(self.request,'No se encontrado ningun dato')
        context['query'] = self.query()
        context['title'] = f'Consulta de Clientes. {self.query()}'
        context['count'] = context['customer_list'].count()
        context['posicion'] = self.query() 
        context['permisos'] = recorrer_los_permisos_usuario(self.request)
        

        return context

Backend/project/templates/snippets/cobranzas.html
{% load static %}
<div class="tasks-card">
    <!-- Header -->
    <div class="tasks-header">
        <h3 class="tasks-title">
            <a href="{% url 'customers:cobranza_asesor' %}">Cobranzas</a>
        </h3>

    </div>

    <!-- Stats -->
    <div class="tasks-stats">
        <p class="stats-text">
            <span class="stats-numbers">{{cobranza.completados}}</span> Cobranzas Realizadas de
            <span class="stats-numbers">{{cobranza.total}}</span>
        </p>
    </div>

    <!-- Tasks Table -->
    <table class="tasks-table">
        <tbody id="tasksTableBody">
            {% for cobro in cobranza.ultimos_10 %}
            <tr class="task-row">
                <td class="task-cell ">
                    <div class="task-main">
                        <p class="task-title">{{cobro.cobranza.credito}}</p>
                        <p class="task-due">{{cobro.cobranza.fecha_registro}}</p>
                    </div>
                </td>
                <td class="task-cell">
                    <div class="task-status">Status</div>
                    <div class="status-badge 
                {% if cobro.cobranza.estado_cobranza == 'Pendiente' %} status-in-progress 
                {% elif cobro.cobranza.estado_cobranza == 'Incumplido' %} status-outdated 
                {% else %} status-completed
                {% endif %}">
                        {{cobro.cobranza.estado_cobranza}}
                    </div>
                </td>

                <td class="task-cell ">
                    <div class="task-time">Fecha Promesa de Pago</div>
                    <div class="time-value">{{ cobro.cobranza.fecha_promesa_pago }} </div>
                </td>
                <td class="task-cell">
                    <div class="task-actions">
                        <a href="{% url 'customers:actualizacion_cobranza' cobro.cobranza.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                                class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path
                                    d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                <path fill-rule="evenodd"
                                    d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                            </svg>
                        </a>
                        <a href="{% url 'customers:eliminacion_cobranza' cobro.cobranza.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                                class="bi bi-trash" viewBox="0 0 16 16">
                                <path
                                    d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z" />
                                <path
                                    d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z" />
                            </svg>
                        </a>





                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

Backend/project/templates/snippets/forms.html
{% load static %}


{% for field in form %}

<div class="form-group">
  <label for="{{ field.id_for_label }}" class="form-label fw-bold">
    {{ field.label }}
  </label>
  {{ field }}
  {% if field.errors %}
  {{ field.errors }}
  {% endif %}
</div>
<br />

{% endfor %}

Backend/project/templates/snippets/graficas.html
{% load static %}
<div class="chart-container">
    <h4>📊 Registro de Clientes</h4>
    <canvas id="myChart"></canvas>
</div>
<div class="chart-container">
    <h4>💳 Registro de Créditos</h4>
    <canvas id="myChartC"></canvas>
</div>

Backend/project/templates/snippets/informacion.html
{% load static %}

<a href="{% url 'customers:customers'%}" class="stat-card">
    <div class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-people-fill"
            viewBox="0 0 16 16">
            <path
                d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5" />
        </svg>
    </div>
    <div class="number">{{clientes.count}}</div>
    <div class="label">Clientes Registrados</div>


</a>

<a href="{% url 'financings:list_credit'%}" class="stat-card">
    <div class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
            class="bi bi-credit-card-2-back-fill" viewBox="0 0 16 16">
            <path
                d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v5H0zm11.5 1a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zM0 11v1a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-1z" />
        </svg>
    </div>
    <div class="number">{{creditos.creditos.count}}</div>
    <div class="label">Créditos Vigentes</div>
</a>

<a href="{% url 'financings:list_credit'%}?status=Creditos en Atraso" class="stat-card">
    <div class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
            class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
            <path
                d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </svg>
    </div>
    <div class="number">{{creditos.creditos_atrasados.count}}</div>
    <div class="label">Créditos en Atraso</div>
</a>

<a href="{% url 'financings:filter_credito_fecha_vencimiento_hoy'%}" class="stat-card">
    <div class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-calendar-event"
            viewBox="0 0 16 16">
            <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z" />
            <path
                d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z" />
        </svg>
    </div>
    <div class="number">{{creditos.creditos_fecha_vencimiento.count}}</div>
    <div class="label">Vencen Hoy</div>
</a>

<a href="{% url 'financings:filter_credito_fecha_limite_hoy'%}" class="stat-card">
    <div class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-clock-fill"
            viewBox="0 0 16 16">
            <path
                d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z" />
        </svg>
    </div>
    <div class="number">{{creditos.creditos_fecha_limite.count}}</div>
    <div class="label">Fecha Límite Hoy</div>
</a>

<a href="{% url 'financings:filter_credito_proximos_vencerse'%}" class="stat-card">
    <div class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-calendar-week"
            viewBox="0 0 16 16">
            <path
                d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z" />
            <path
                d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z" />
        </svg>
    </div>
    <div class="number">{{creditos.creditos_proximos_vencerse.count}}</div>
    <div class="label">Próximos a Vencer</div>
</a>

Backend/project/templates/snippets/pages.html
{% load static %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-auto">
      <nav aria-label="Paginación responsive">
        <ul class="pagination flex-wrap justify-content-center">

          {# Botón anterior #}

          {% if page_obj.has_previous %}
            <li class="page-item">
              {% if query %}
              <a class="page-link" href="?q={{ query }}&?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
                <span aria-hidden="true">&laquo;</span>
              </a>
              {% else %}
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
                <span aria-hidden="true">&laquo;</span>
              </a>
              {% endif %}
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">&laquo;</span>
            </li>
          {% endif %}

          {# Números de página #}
          {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
              <li class="page-item active" aria-current="page">
                <a class="page-link" style="background-color:#fea3a5; color: #46090a; border: 1px solid #fea3a5;">{{ num }}</a>
              </li>
            {% else %}
              <li class="page-item">
                {% if query %}
                <a class="page-link" href="?q={{ query }}&?page={{ num }}" style="color: black;">{{ num }}</a>
                {% else %}
                <a class="page-link" href="?page={{ num }}" style="color: black;">{{ num }}</a>
                {% endif %}
              </li>
            {% endif %}
          {% endfor %}

          {# Botón siguiente #}
          {% if page_obj.has_next %}
            <li class="page-item">
              {% if query %}
                <a class="page-link" href="?q={{ query }}&?page={{ page_obj.next_page_number }}" style="color: black;">
                  <span aria-hidden="true">&raquo;</span>
                </a>
                {% else %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Siguiente">
                <span aria-hidden="true">&raquo;</span>
              </a>
                {% endif %}

              
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">&raquo;</span>
            </li>
          {% endif %}

        </ul>
      </nav>
    </div>
  </div>
</div>

Backend/project/templates/snippets/recibos.html
{% load static %}

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Fecha</th>
            <th scope="col">Nombre del Cliente</th>
            <th scope="col">Codigo del Credito</th>
            <th scope="col">Numero de Referencia</th>
            <th scope="col">Monto</th>
            
            <th scope="col">...</th>

        </tr>
    </thead>
    <tbody>
        {% for recibo in recibos %}
        <tr>
            <th scope="row">
                {{ forloop.counter }}
            </th>
            <td>{{recibo.fecha}}</td>
            <td>

                {% if recibo.pago.credit %}
                    {{recibo.cliente}}

                {% elif recibo.pago.acreedor %}

                    {{recibo.pago.acreedor.nombre_acreedor}}

                {% elif recibo.pago.seguro %}

                    {{recibo.pago.seguro.nombre_acreedor}}

                {% endif %}

                
            </td>
            <td>
                {% if recibo.pago.credit %}

                    {{recibo.pago.credit.codigo_credito}}

                {% elif recibo.pago.acreedor %}

                    {{recibo.pago.acreedor.codigo_acreedor}}

                {% elif recibo.pago.seguro %}

                    {{recibo.pago.seguro.codigo_seguro}}

                {%endif%}
                

            </td>
            <td>{{recibo.pago.numero_referencia}}</td>
            <td>Q{{recibo.Ftotal}}</td>
            <td>
                <a href="{% url 'financings:factura' recibo.id%}">Facturar</a>
            </td>
        </tr>
        {% endfor%}

    </tbody>
</table>

Backend/project/templates/snippets/search.html
<nav class="navbar navbar-expand-lg navbar-light bg-light  ">
    <div class="container-fluid">

        <form class="d-flex" action="{% url 'busqueda_general' %}">
            <a class="nav-link" aria-disabled="true" style="margin-right: 1rem">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                    class="bi bi-bell-fill" viewBox="0 0 16 16">
                    <path
                        d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2m.995-14.901a1 1 0 1 0-1.99 0A5 5 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901" />
                </svg>
            </a>
            <input class="form-control me-2" name="q" value="{{ query }}" type="search" placeholder="Buscar"
                aria-label="Search">
            <button class="btn_outline" type="submit">Buscar</button>
        </form>

    </div>
</nav>