Backend/project/apps/accountings/urls.py
# URL
from django.urls import path, include

# Views
from . import views

# FILTROS

# Decorador
from django.contrib.auth.decorators import login_required

# Routes
from apps.accountings.api import routers


app_name = 'contable'

urlpatterns = [
    path('',views.list_modulos,name='modulos_contables'),
    path('reports/acreedores/',login_required(views.reportes_generales_acreedores),name='reportes_acreedores'),
    path('reports/seguros/',login_required(views.reportes_generales_seguros),name='reportes_seguros'),
    # LIST
    path('acreedores/', views.AcreedoresListView.as_view(), name='acreedores'),
    path('seguros/', views.SeguroListView.as_view(), name='seguros'),
    path('ingresos/', login_required( views.IngresosList.as_view()), name='ingresos'),
    path('egresos/', login_required(views.EgresosList.as_view()), name='egresos'),

    # CREATE
    path('acreedores/create/', views.add_acreedor, name='acreedores_create'),
    path('seguros/create/', views.add_seguro, name='seguros_create'),
    path('ingresos/create/', views.add_ingreso, name='ingresos_create'),
    path('egresos/create/', views.add_egresos, name='egresos_create'),

    # DETAIL
    path('acreedores/detail/<int:id>/', views.detail_acreedores, name='acreedores_detail'),
    path('seguros/detail/<int:id>/', views.detail_seguro, name='seguros_detail'),
    path('ingresos/detail/<int:id>/', views.detail_ingreso, name='ingresos_detail'),
    path('egresos/detail/<int:id>/', views.detail_egreso, name='egresos_detail'),

    # BOLETAS
    path('seguros/boleta/', views.add_boleta_seguro, name='seguros_boleta'),
    path('acreedores/boleta/', views.add_boleta_acreedor, name='acreedores_boleta'),

    # UPDATE
    path('egresos/update/<int:id>/',views.actualizar_egresos, name='egresos_update'),
    path('ingresos/update/<int:id>/',views.actualizar_ingresos, name='ingresos_update'),


    # SEARCH 
    path('acreedores/search/', views.AcreedoresSearch.as_view(), name='acreedores_search'),
    path('seguros/search/', views.SeguroSearch.as_view(), name='seguros_search'),
    path('ingresos/search/', views.IngresoSearch.as_view(), name='ingresos_search'),
    path('egresos/search/', views.EgresoSearch.as_view(), name='egresos_search'),

    # FILTRO
    path('ingresos/pendiente/', views.pendiente_ingresos_vincular, name='pendiente_ingresos_vincular'),
    path('ingresos/completados/', views.ingresos_vinculados, name='ingresos_vinculados'),

    path('egresos/pendiente/', views.pendiente_egresos_vincular, name='pendiente_egresos_vincular'),
    path('egresos/completados/', views.egresos_vinculados, name='egresos_vinculados'),
    
    path('seguros/seguros_cancelados/',views.seguro_cancelado, name='seguro_cancelado'),
    path('seguros/atraso_en_aportacion/',views.seguros_atraso_aportacion, name='seguros_atraso_aportacion'),
    path('seguros/atraso_por_fechas/',views.seguros_atraso_fechas, name='seguros_atraso_fechas'),

    path('acreedores/acreedores_cancelados/',views.acreedores_cancelado, name='acreedores_cancelado'),
    path('acreedores/atraso_en_aportacion/',views.acreedores_atraso_aportacion, name='acreedores_atraso_aportacion'),
    path('acreedores/atraso_por_fechas/',views.acreedores_atraso_fechas, name='acreedores_atraso_fechas'),

    
]

urlpatterns+=routers.urlpatterns

Backend/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

# Vistas
from . import views
from apps.actividades.views  import subida_documento

from django.contrib.auth import views as auth_views
from . import generate_pdf



# CONFIGURANCION PARA MANEJAR LOS STATICS Y MEDIA
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required



from django.conf.urls import handler404, handler500, handler400, handler403
from .http import request_400

from django.core.mail import send_mail
from django.conf import settings

from django.urls import re_path
from django.views.static import serve
from django.conf import settings

# RUTAS
from .rutas import urlpatterns_apps, urlpatterns_api, urlpatterns_reports, urlpatterns_http


urlpatterns = [    
    path('',login_required(views.index),name='index'),
    path('accounts/login/',views.login_view, name='login'),
    path('verification/', views.verification, name='verification'),
    path('logout/',views.logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('search/', login_required(views.Search.as_view()), name='busqueda_general'),
    path('qr/<str:data>/', views.generate_qr, name='generate_qr'),
    path('pdf/<int:id>', generate_pdf.generar_pdf, name='pdf'),
    path('boleta_procesada/', views.agradecimeinto, name='boleta_procesada'),
    path('cliente/<str:uuid>/', subida_documento, name='subida_documento_cliente'),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += urlpatterns_apps + urlpatterns_api + urlpatterns_reports + urlpatterns_http

#template_name='user/autentication/password-reset.html'
#email_template_name='user/autentication/password-message.html'

handler404 = request_400.error404

Backend/project/apps/accountings/forms/ingresos.py
# Formulario
from django import forms

# Models
from apps.accountings.models import Income


# Tiempo
from datetime import datetime

from django import forms


class IngresoForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = [
            'fecha',
            'monto',
            'numero_referencia',
            'codigo_ingreso',
            'descripcion',
            'observaciones',
            
            'boleta'
        ]
        labels = {
            'fecha': 'Fecha',
            'monto': 'Monto',
            'codigo_ingreso': 'Código de Ingreso',
            'descripcion': 'Descripción',
            'observaciones': 'Observaciones',
            'numero_referencia': 'Número de Referencia',
            'boleta': 'Boleta'
        }
        widgets = {
            'fecha': forms.TextInput(attrs={'type': 'date', 'class': 'form-control'}),
            'monto': forms.TextInput(attrs={'class': 'form-control', 'type': 'number', 'min': '0','step':'any'}),
            'codigo_ingreso': forms.Select(choices=[],attrs={'class': 'form-control'}),  # Se definirá más adelante.
            'observaciones': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
            'numero_referencia': forms.TextInput(attrs={'class': 'form-control'}),
            'boleta':forms.FileInput(attrs={'type':'file','class':'form-control','name':'document','accept':'.pdf, .doc, .docx,.xls,.xlsx,.txt,image/*'}),  
        }   

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Opciones para el campo 'codigo_ingreso' (pueden venir de la base de datos)
        opciones_codigo_ingreso = [
            ('', 'Seleccione un código'),  # Opción inicial
            ('Servicios terceros', 'Servicios terceros'),
            ('Otros Ingresos', 'Otros Ingresos'),
        ]

        # Asignar las opciones al widget 'Select'
        self.fields['codigo_ingreso'].widget.choices = opciones_codigo_ingreso


       

Backend/project/templates/contable/ingresos/table/table.html
{% load static %}
<div class="row">
    <div class="col-12 " style="text-align: center;">
        <div class="table-responsive">
            <table class="table table-hover table-sm">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Codigo de Ingreso</th>

                        <th scope="col">Fecha</th>
                        <th scope="col">Monto</th>
                        <th scope="col">Numero de Referencia</th>
                        <th scope="col">Fecha De Registro</th>
                        <th scope="col">Status</th>



                    </tr>
                </thead>
                <tbody>
                    {% for acreedor in object_list %}


                    <tr>
                        <td>
                            <a href="{% url 'contable:ingresos_detail' acreedor.id %}"
                            style="text-decoration: none; color: #00340c;">
                            {{ forloop.counter }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'contable:ingresos_detail' acreedor.id %}"
                            style="text-decoration: none; color: #00340c;">
                            {{acreedor.codigo_ingreso}}
                            </a>
                        
                        </td>
                        <td>
                            <a href="{% url 'contable:ingresos_detail' acreedor.id %}"
                            style="text-decoration: none; color: #00340c;">
                            {{acreedor.fecha}}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'contable:ingresos_detail' acreedor.id %}"
                            style="text-decoration: none; color: #00340c;">
                            Q{{acreedor.fmonto}}
                            </a>
                        
                        </td>
                        <td>
                            <a href="{% url 'contable:ingresos_detail' acreedor.id %}"
                            style="text-decoration: none; color: #00340c;">
                            {{acreedor.numero_referencia}}
                            </a>
                        
                        </td>
                        <td>
                            <a href="{% url 'contable:ingresos_detail' acreedor.id %}"
                            style="text-decoration: none; color: #00340c;">
                            {{acreedor.fecha_registro}}
                            </a>
                        </td>
                        <td>
                            {% if acreedor.status %}
                            <div class="activo ">
                                <a href="{% url 'contable:ingresos_detail' acreedor.id %}"
                                    style="text-decoration: none; color: #00340c;">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                        class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                                        <path
                                            d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
                                    </svg>

                                </a>


                            </div>
                            {% else %}
                            <div class=" inactivo ">
                                Pendiente de vincular


                            </div>
                            {% endif %}

                         
                        </td>
                        
                    </tr>






                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


</div>