Backend/project/apps/addresses/urls.py
# URL
from django.urls import path, include

# VIEWS
from . import views

#API
from apps.addresses.api import routers

# Decorador
from django.contrib.auth.decorators import login_required

app_name = 'addresses'

urlpatterns = [
    path('add/<str:customer_code>/', login_required( views.AddressCreateView.as_view()), name = 'add'),
    path('update/<int:id>/<str:customer_code>/', login_required(views.addressUpdateView), name = 'update'),
    path('municipio/crear/',login_required(views.crear_municipio),name='crear_municipio'),
]

urlpatterns+=routers.urlpatterns

Backend/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

# Vistas
from . import views
from apps.actividades.views  import subida_documento

from django.contrib.auth import views as auth_views
from . import generate_pdf



# CONFIGURANCION PARA MANEJAR LOS STATICS Y MEDIA
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required



from django.conf.urls import handler404, handler500, handler400, handler403
from .http import request_400

from django.core.mail import send_mail
from django.conf import settings

from django.urls import re_path
from django.views.static import serve
from django.conf import settings

# RUTAS
from .rutas import urlpatterns_apps, urlpatterns_api, urlpatterns_reports, urlpatterns_http


urlpatterns = [    
    path('',login_required(views.index),name='index'),
    path('accounts/login/',views.login_view, name='login'),
    path('verification/', views.verification, name='verification'),
    path('logout/',views.logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('search/', login_required(views.Search.as_view()), name='busqueda_general'),
    path('qr/<str:data>/', views.generate_qr, name='generate_qr'),
    path('pdf/<int:id>', generate_pdf.generar_pdf, name='pdf'),
    path('boleta_procesada/', views.agradecimeinto, name='boleta_procesada'),
    path('cliente/<str:uuid>/', subida_documento, name='subida_documento_cliente'),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += urlpatterns_apps + urlpatterns_api + urlpatterns_reports + urlpatterns_http

#template_name='user/autentication/password-reset.html'
#email_template_name='user/autentication/password-message.html'

handler404 = request_400.error404

Backend/project/apps/addresses/forms.py
from django import forms

# Models
from .models import Address

class AddressForms(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            'street',
            'number',
            'city',
            'state',
            'country',
            'latitud',
            'longitud',
            'type_address'
            
            ]

        labels = {
            'street':'Dirección particular o sede social completa (*)',
            'number':'Zona (*)',
            'city':'Departamento (*)',
            'state':'Municipio (*)',
            
            'country':'País (*)',
            'type_address':'Tipo de direccion (*)',
            'latitud':'Latitud (*)',
            'longitud':'Longitud (*)'
            
            

        }

        
        widgets = {
            'street': forms.TextInput(attrs={'class':'form-control'}),
            'number': forms.TextInput(attrs={'class':'form-control','type':'number','min':'0'}),
            'city': forms.Select(attrs={'class':'form-control city1','required':'required'}),
            'state': forms.Select(attrs={'class':'form-control state1','required':'required'}),
            
            'country': forms.TextInput(attrs={'class':'form-control'}),
            'type_address':forms.Select(attrs={'class':'form-control'}),
            'latitud': forms.TextInput(attrs={'class':'form-control'}),
            'longitud': forms.TextInput(attrs={'class':'form-control'}),
           
            

        }

    def __init__(self, *args, **kwargs):
        super(AddressForms, self).__init__(*args, **kwargs)

        self.fields['state'].required = True
        self.fields['city'].required = True
       
        

Backend/project/apps/addresses/api/views.py
from rest_framework import generics

# Serializador
from .serializers import AddressSerializaer, MunicipioSerializaer, DepartamentoSerializaer

# API
from rest_framework import viewsets, status, generics
from rest_framework.views import APIView
from rest_framework.response import Response

# Model
from apps.addresses.models import Address, Municiopio, Departamento

# HISTORIAL Y BITACORA
from apps.actividades.utils import log_user_action, log_system_event
from scripts.conversion_datos import model_to_dict, cambios_realizados

import traceback
from rest_framework import status
from rest_framework.exceptions import ValidationError

class AddressViewSet(viewsets.ModelViewSet):
    serializer_class = AddressSerializaer
    queryset = Address.objects.all()

    def perform_create(self, serializer):
        try:
            direccion = serializer.save()
            user = self.request.user
            
            log_user_action(
                user=user,
                action="Creación de Direccion",
                details=f"Se creó la dirección de  {direccion.type_address}.",
                request=self.request,
                category_name="Direccion",
                metadata=model_to_dict(direccion)
            )
        except Exception as e:
            # 3. Si algo falla, capturamos el error y el traceback
            error_stack = traceback.format_exc()
            
            log_system_event(
                message=f"Error al crear una direccion o registrar log: {str(e)}",
                level_name="ERROR",
                source="AddressViewSet.perform_create",
                category_name="Direccion",
                traceback=error_stack,
                metadata={
                    "request_data": self.request.data,
                    "user_attempting": str(self.request.user)
                }
            )
            
            # 4. Relanzamos una excepción para que el cliente reciba un error 400/500
            raise ValidationError({
                "error": "No se pudo completar la operación. El incidente ha sido reportado al sistema."
            })
    
    def perform_update(self, serializer):
        try:
            instance = self.get_object()
            previous_data = model_to_dict(instance)
            direccion = serializer.save()
            new_data = model_to_dict(direccion)

            changes = {
                "antes": previous_data,
                "despues": new_data
            }

            log_user_action(
                user=self.request.user,
                action="Actualización de Direccion",
                details=f"Se actualizó la direccion {direccion.id}.",
                request=self.request,
                category_name="Direccion",
                metadata=changes
            )

        except Exception as e:
            # 3. Si algo falla, capturamos el error y el traceback
            error_stack = traceback.format_exc()
            
            log_system_event(
                message=f"Error al actualizar la direccion o registrar log: {str(e)}",
                level_name="ERROR",
                source="AddressViewSet.perform_update",
                category_name="Direccion",
                traceback=error_stack,
                metadata={
                    "request_data": self.request.data,
                    "user_attempting": str(self.request.user)
                }
            )
            
            # 4. Relanzamos una excepción para que el cliente reciba un error 400/500
            raise ValidationError({
                "error": "No se pudo completar la operación. El incidente ha sido reportado al sistema."
            })
    
    def perform_destroy(self, instance):
        direccion_data = model_to_dict(instance)
        

        log_user_action(
            user=self.request.user,
            action="Eliminación de Dirección",
            details=f"Se eliminó la dirección {instance.id}",
            request=self.request,
            category_name="Direccion",
            metadata=direccion_data
        )

        try:
            instance.delete()
            log_user_action(
                user=self.request.user,
                action="Eliminación de Direccion",
                details=f"Se eliminó la dirección {instance.id}",
                request=self.request,
                category_name="Direccion",
                metadata=direccion_data
            )

        except Exception as e:
            import traceback
            log_system_event(
                message=f"Error al eliminar la direccion {instance.id}: {str(e)}",
                level_name="ERROR",
                source="AddressViewSet.perform_destroy",
                category_name="Direccion",
                traceback=traceback.format_exc(),
                metadata=direccion_data
            )
            raise  


class MunicipioViewSet(viewsets.ModelViewSet):
    serializer_class = MunicipioSerializaer
    queryset = Municiopio.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        search_term = self.request.query_params.get('term', '')  # Obtener el parámetro 'term'
        if search_term:
            queryset = queryset.filter(nombre__icontains=search_term)  # Filtrar por el término de búsqueda
        return queryset

    def perform_create(self, serializer):
        try:
            municipio = serializer.save()
            user = self.request.user
            
            log_user_action(
                user=user,
                action="Creación de Municipio",
                details=f"Se creó el siguiente municipio {municipio.nombre}.",
                request=self.request,
                category_name="Direccion",
                metadata=model_to_dict(municipio)
            )
        except Exception as e:
            # 3. Si algo falla, capturamos el error y el traceback
            error_stack = traceback.format_exc()
            
            log_system_event(
                message=f"Error al crear un municipio o registrar log: {str(e)}",
                level_name="ERROR",
                source="MunicipioViewSet.perform_create",
                category_name="Direccion",
                traceback=error_stack,
                metadata={
                    "request_data": self.request.data,
                    "user_attempting": str(self.request.user)
                }
            )
            
            # 4. Relanzamos una excepción para que el cliente reciba un error 400/500
            raise ValidationError({
                "error": "No se pudo completar la operación. El incidente ha sido reportado al sistema."
            })
    
    def perform_update(self, serializer):
        try:
            instance = self.get_object()
            previous_data = model_to_dict(instance)
            direccion = serializer.save()
            new_data = model_to_dict(direccion)

            changes = {
                "antes": previous_data,
                "despues": new_data
            }

            log_user_action(
                user=self.request.user,
                action="Actualización de Municipio",
                details=f"Se actualizó el municipio {direccion.nombre}.",
                request=self.request,
                category_name="Direccion",
                metadata=changes
            )
        except Exception as e:
            # 3. Si algo falla, capturamos el error y el traceback
            error_stack = traceback.format_exc()
            
            log_system_event(
                message=f"Error al actualizar un municipio o registrar log: {str(e)}",
                level_name="ERROR",
                source="MunicipioViewSet.perform_update",
                category_name="Direccion",
                traceback=error_stack,
                metadata={
                    "request_data": self.request.data,
                    "user_attempting": str(self.request.user)
                }
            )
            
            # 4. Relanzamos una excepción para que el cliente reciba un error 400/500
            raise ValidationError({
                "error": "No se pudo completar la operación. El incidente ha sido reportado al sistema."
            })
    
    def perform_destroy(self, instance):
        direccion_data = model_to_dict(instance)
        

        log_user_action(
            user=self.request.user,
            action="Eliminación de Municipio",
            details=f"Se eliminó el municipio {instance.nombre}",
            request=self.request,
            category_name="Direccion",
            metadata=direccion_data
        )

        try:
            instance.delete()
            log_user_action(
                user=self.request.user,
                action="Eliminación de Municipio",
                details=f"Se eliminó el municipio {instance.nombre}",
                request=self.request,
                category_name="Direccion",
                metadata=direccion_data
            )

        except Exception as e:
            import traceback
            log_system_event(
                message=f"Error al eliminar el municipio {instance.id}: {str(e)}",
                level_name="ERROR",
                source="MunicipioViewSet.perform_destroy",
                category_name="Direccion",
                traceback=traceback.format_exc(),
                metadata=direccion_data
            )
            raise  



class DepartamentoViewSet(viewsets.ModelViewSet):
    serializer_class = DepartamentoSerializaer
    queryset = Departamento.objects.all()
    def get_queryset(self):
        queryset = super().get_queryset()
        search_term = self.request.query_params.get('term', '')  # Obtener el parámetro 'term'
        if search_term:
            queryset = queryset.filter(nombre__icontains=search_term)  # Filtrar por el término de búsqueda
        return queryset

    def perform_create(self, serializer):
        try:

Backend/project/apps/addresses/views.py
# URL
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect

# FORMS
from .forms import AddressForms

# MODELS
from .models import Address
from apps.customers.models import Customer

# CRUD
from django.views.generic import CreateView

# Scripts
from scripts.recoleccion_permisos import recorrer_los_permisos_usuario

# DECORADORES
from django.contrib.auth.decorators import login_required
from project.decorador import usuario_activo, usuario_secretaria, usuario_administrador
from django.utils.decorators import method_decorator

# Create your views here.
# MENSAJES
from django.contrib import messages

# --- CREAR DIRECCION NUEVA --- #
class AddressCreateView(CreateView):
    @method_decorator([usuario_activo])
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request,customer_code, *args, **kwargs):
        template_name = 'addresses/address_add.html'
        cliente = get_object_or_404(Customer, customer_code= str(customer_code))
        
        context = {
            'permisos':recorrer_los_permisos_usuario(request),
            'form':AddressForms,            
            'customer_code':cliente.customer_code
        }
        return render(request, template_name, context)

    def post(self, request, customer_code,*args, **kwargs):
        
        cliente = get_object_or_404(Customer, customer_code= str(customer_code))
        form = AddressForms(request.POST)
       

        if form.is_valid():
            direccion = form.save(commit=False)

            direccion.customer_id = cliente

            
            direccion.save()
            
            
            return redirect('customers:detail',cliente.customer_code ) 
          
        else:
            return self.render_to_response(self.get_context_data(form=form))

# --- ACTUALIZAR DIRECION -----
@usuario_activo
@login_required
@usuario_administrador
def addressUpdateView(request, id,customer_code):

    template_name = 'addresses/address_update.html'

    cliente = get_object_or_404(Customer, customer_code= str(customer_code))
    address = get_object_or_404(Address,id=id)

    if request.method == 'POST':
        form = AddressForms(request.POST, instance=address)
        if form.is_valid():
            formulario = form.save(commit=False)

            formulario.save()
            return redirect('customers:detail',cliente.customer_code ) 
       
           

    form = AddressForms(instance=address)

    context = {
        'form':form,
        'permisos':recorrer_los_permisos_usuario(request),
    }
    
    return render(request, template_name, context)

@login_required
@usuario_activo
def crear_municipio(request):
    template_name = 'addresses/created_municipio.html'
    context = {
        'permisos':recorrer_los_permisos_usuario(request),
    }
    return render(request, template_name, context)

Backend/project/templates/addresses/address_add.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="container box">
    <form method="POST" action="{% url 'addresses:add' customer_code %}" >
        {% csrf_token %}
        <div class="row">
            {% include 'addresses/forms/address_forms.html' %}

        </div>
        
        <div class="row" style="margin-top: 1rem;">
            <div class="col">
                <button onclick="window.history.back()" type="button" class="btn_cancel">Cancelar</button>

            </div>
            <div class="col">
                <button type="submit" class="btn_guardar">Siguiente</button>

            </div>



        </div>
       


    </form>
</div>
    
{% endblock %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script type="text/javascript" src="{% static 'js/customer/seleccionar.js'%}"></script>

{% endblock %}

Backend/project/templates/addresses/address_update.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="container box">
    <form method="POST" >
        {% csrf_token %}
        <div class="row">
            {% include 'addresses/forms/address_forms.html' %}

        </div>
        
        <div class="row" style="margin-top: 1rem;">
            <div class="col">
                <button onclick="window.history.back()" type="button" class="btn_cancel">Cancelar</button>

            </div>
            <div class="col">
                <button type="submit" class="btn_guardar">Siguiente</button>

            </div>



        </div>
       


    </form>
</div>
    
{% endblock %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script type="text/javascript" src="{% static 'js/customer/seleccionar.js'%}"></script>

{% endblock %}

Backend/project/templates/addresses/created_municipio.html
{% extends 'base.html'%}
{% load static %}
{% block css %}
<!--SELECT-->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

{% endblock%}
{% block content %}
<div class="row box">
    <form method="POST" enctype="multipart/form-data" autocomplete="off" id="municipio">
        {% csrf_token %}
        <meta name="csrf-token" content="{{ csrf_token }}">
        <div class="form-group">
            <label for="nombre" style="font-weight: 600;">Nombre del Municipio</label>
            <input type="text" name="nombre" id="nombre" class="form-control">

        </div>
        <div class="form-group" style="margin-top: 1rem;">
            <label for="departamento" style="font-weight: 600;">Departamento que pertenece este municipio</label>
            <select name="departamento" id="depart" class="depart" style="width: 100%;"></select>

        </div>
        <div style="margin-top: 1rem;">
            <button type="submit" class="btn_guardar">Crear Registro</button>
            <button onclick="window.history.back()" type="button" class="btn_cancel">Cancelar</button>
        </div>

    </form>

</div>


{% endblock %}

{% block js %}
<script type="module" src="{% static 'js/direcion/municipio/crear.js' %}"></script>
<script>
    // Obtener el protocolo (HTTP/HTTPS)
    const protocolo = window.location.protocol; // Ejemplo: "https:"

    // Obtener el dominio (hostname)
    const dominio = window.location.hostname; // Ejemplo: "example.com"

    // Obtener el puerto
    const puerto = window.location.port; // Ejemplo: "8080" o "" si no está explícito
    const baseUrl = `${protocolo}//${dominio}${puerto ? `:${puerto}` : ''}`;
    $(document).ready(function () {
        $('.depart').select2({
            ajax: {
                url: `${baseUrl}/addresses/api/departamento/`,
                dataType: 'json',
                delay: 250,
                data: function (params) {
                    return {
                        term: params.term // Parámetro que el backend debe esperar
                    };
                },
                processResults: function (data) {
                    console.log(data);
                    // Verificar si 'data' es un array de objetos
                    if (Array.isArray(data)) {
                        return {
                            results: data.map(function (item) {
                                console.log(item);
                                return {
                                    id: item.id,
                                    text: item.nombre
                                };
                            })
                        };
                    } else {
                        console.error('Estructura de datos inesperada:', data);
                        return {
                            results: []
                        };
                    }
                },
                cache: true
            },
            placeholder: 'Seleccione un Departamento',
            minimumInputLength: 1

        });
    });
</script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
{% endblock%}